version: '3.1'
services:

  <%= appName %>:
    build: ../
    container_name: <%= appName %>
    <%_ if (distTracing === true) { _%>
    environment:
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
    <%_ } _%>
    ports:
      - "8080:8080"
      - "8083:8383"
    restart: always
    <%_ if (distTracing === true) { _%>
    links:
      - jaeger
    <%_ } _%>

<%_ if (databaseType === 'postgresql') { _%>
  postgresqldb:
    image: postgres:10.7
    container_name: postgresqldb
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
<%_ } _%>
<%_ if (databaseType === 'mysql') { _%>
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE: appdb
      - MYSQL_USER: siva
      - MYSQL_PASSWORD: secret
      - MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  <%_ } _%>

<%_ if (elkjaeger === true) { _%>
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    environment:
      - "SERVER_NAME=kibana"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601
    links:
      - elasticsearch
  <%_ } _%>


<%_ if (distTracing === true) { _%>
  jaeger:
    image: jaegertracing/all-in-one:1.12
    <%_ if (elkjaeger === true) { _%>
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
      - "ES_TAGS_AS_FIELDS_ALL=true"
    <%_ } _%>
    ports:
      - "16686:16686"
    restart: on-failure
    <%_ if (elkjaeger === true) { _%>
    links:
      - elasticsearch
    <%_ } _%>
<%_ } _%>
